-- 1.DDL
-- 1-1 다른 테이블 참조하여 테이블 생성
CREATE TABLE COURSE_PROFESSOR(CNO, CNAME, PNO, PNAME, AVGRES)
AS
SELECT CNO, C.CNAME, PNO, P.PNAME, ROUND(AVG(RESULT), 2)
FROM COURSE C
         NATURAL JOIN PROFESSOR P
         NATURAL JOIN SCORE C
GROUP BY CNO, C.CNAME, PNO, P.PNAME

SELECT *
FROM COURSE_PROFESSOR

-- STUDENT의 SNO, SNAME,MAJOR,SYEAR, SCORE의 학생들의 RESULT , SCGRADE의 GRADE 가지는 테이블 생성
CREATE TABLE T_ST(SNO, SNAME, MAJOR, SYEAR, RESULT, GRADE)
AS
SELECT SNO, S.SNAME, S.MAJOR, S.SYEAR, S2.RESULT, SG.GRADE
FROM SCGRADE SG,
     STUDENT S
         NATURAL JOIN C##MG.SCORE S2
WHERE RESULT BETWEEN LOSCORE AND HISCORE

select *
from T_ST
order by RESULT desc;


-- 1-2 ALTER
-- 컬럼을 추가하는 ADD
-- EMP_COPY 테이블에 ADDR

ALTER TABLE EMP_COPY
    ADD ADDR VARCHAR2(50)

SELECT *
FROM EMP_COPY

-- 컬럼명을 변경하는 RENAME
-- EMP_COPY 테이블의 SAL컬럼을 SALARY 변경
ALTER TABLE EMP_COPY
    RENAME COLUMN SAL TO SALARY

select *
from EMP_COPY;

-- 컬럼의 데이터타입을 변경하는 MODIFY
-- EMP_COPY 테이블의 ENO컬럼의 데이터타입을 VARCHAR2(4) -> VARCHAR2(10)
ALTER TABLE EMP_COPY
    MODIFY ENO VARCHAR2(10)

-- 컬럼을 삭제하는 DROP
-- EMP_COPY 테이블에 ADDR컬럼 삭제
ALTER TABLE EMP_COPY
    DROP COLUMN ADDR;

select *
from EMP_COPY;

-- 1-3 테이블을 삭제하는 DROP
CREATE TABLE emp_copy
AS
SELECT *
FROM emp

-- 1-4 RENAME
RENAME EMP_COPY TO EMP_TEMP

drop table emp_temp

select *
from EMP_TEMP;


-- 1-5 테이블의 데이터를 모두 삭제하는 truncate
truncate table EMP_TEMP